wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.12
    start_time: 1641926228
    t:
      1:
      - 1
      2:
      - 1
      4: 3.6.12
      5: 0.12.9
      8:
      - 2
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 1000
img_scale:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 1.0e-06
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
